version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "22022:27017"
    environment:
      MONGO_INITDB_DATABASE: kakebo
    volumes:
      - mongo_data:/data/db
    # (Opcional) quita/ajusta el healthcheck si te molestan los logs
    # healthcheck:
    #   test: ["CMD-SHELL", "mongosh --eval 'db.adminCommand(\"ping\")' || exit 1"]
    #   interval: 60s
    #   timeout: 5s
    #   retries: 2

  app:
    container_name: go-api
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: ./backend
  
  web:
    build:
      context: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - app

volumes:
  mongo_data:
